### ISSUE TITLE
浮水印無法顯示

### ISSUE THREAD

**Issue by blackpepperlolz** [sppmg/TW_Thesis_Template#16]
您好:

我根據Wiki修改config.tex讀取浮水印，並於main.tex加入\startWatermark
但依舊無法顯示浮水印，浮水印兩個方法都有編譯測試過，
我是使用xelatex編譯

**Comment by sppmg** [comment]
抱歉晚回了！請問解決了嗎？

如果還沒的話，請問：

1. 編譯後是否有任何錯誤訊息？有的話請提供。
2. 你的浮水印格式？（或是提供學校與網路連結方便我測試）
3. 是否在未修改的樣板檔測試過？
4. `兩個方法` 是指`background` 與 `eso-pix`嗎？
5. 使用平台？windows? `miktex` or `tex live` ?

我[最新版](https://github.com/sppmg/TW_Thesis_Template/blob/master/CHANGELOG.md#v182-2019-04-07)應該是不須要再手動添加 `\startWatermark` 才是 (wiki 應該是忘記改了。)

**Comment by blackpepperlolz** [comment]
您好:

1. 編譯後是否有任何錯誤訊息？有的話請提供。
    可以成功編譯，無任錯誤訊息
2. 你的浮水印格式？（或是提供學校與網路連結方便我測試）
    我是使用NCTU格式，直接使用樣板內的lodo.pdf檔案
3. 是否在未修改的樣板檔測試過？
    有的，我用NCTU_PATCH產生樣板後，直接編譯也是無浮水印。
    測試其他樣板也是無法顯示。
4. 兩個方法 是指background 與 eso-pix嗎？
    是的
5. 使用平台？windows? miktex or tex live ?
   使用平台為 Window，套件包為miktex

另外我有使用`\wallpaper`的作法，是可以成功的
文件中的其他圖片都能成功讀取顯示，所以路徑設定是沒問題的

再麻煩您 謝謝

**Comment by sppmg** [comment]
你是不是 `publish` 沒設成 `true` ？
其實[註解有提醒](https://github.com/sppmg/TW_Thesis_Template/blob/f961234c216ad9542e276e2b767673b5f672c8cd/NCTU_patch/config.tex#L163)要設定喔！

這功能是為了閱讀方便設定的。
因為有些學校提供的 logo 太深，會影響閱讀。如果只是要印給口委、教授看的話就不用顯示。
`publish` 是最後繳交正式版本用的，原設計概念就是此時才加上浮水印。

**Comment by blackpepperlolz** [comment]
您好:
對的，我Publish並沒有設成true。
謝謝特別抽空解答，
