### ISSUE TITLE
在表格中插入圖片

### ISSUE THREAD

**Issue by 7nightingale6** [sppmg/TW_Thesis_Template#18]
您好，我在表格中用您的指令(\fig[][][]{}[][])插入圖片時發生錯誤
錯誤訊息：not in outer par mode
我原先猜想是因為浮動的關係 所以把浮動改成h 結果還是出現同一個錯誤訊息
我用的是MikTeX / Texmaker / Windows
大概就是這樣直接插入表格：
\begin{tabular}{|c|c|c|} \hline
\fig[][][h]{}[][] & \fig[][][h]{}[][] & \fig[][][h]{}[][] \\ \hline
\end{tabular}
請問這個寫法該怎麼改呢

**Comment by sppmg** [comment]
figure 環境好像不能在 tabular 裡面。
（\fig 是為了速寫用的，會展開成 figure + includegraphics)

下面連結是使用 includegraphics 插入 tabular：（也可以用 minipage 達成）

https://tex.stackexchange.com/q/301992

如果你是要並列多張圖，我個人推薦用 subcaptionbox。它還可以對單張子圖編號 a,b,c, 。
可以看一下我教學的那個說明（記得樣板也有範例的樣子）。


7nightingale6 ***@***.***> 於 2021年5月20日 週四 下午10:37 寫道：

**Comment by 7nightingale6** [comment]
成功了!謝謝!!
