### ISSUE TITLE
main無法編譯

### ISSUE THREAD

**Issue by 7nightingale6** [sppmg/TW_Thesis_Template#21]
您好
每一個檔案分開編譯的時候都沒有問題，但是編譯總檔的時候就跑不動(之前有成功過)，一直是藍圈圈，連錯誤訊息都沒出現。請問有可能是什麼問題？要怎麼解決？謝謝！
我用的是MikTeX / Texmaker / Windows

(我的文件只剩總檔編譯就完成了，已經處理兩天了還是只會跑藍圈圈，我快瘋了QQ)

**Comment by sppmg** [comment]
首先先看 log，texmaker 我沒用過，看看能否看到即時的 log。
能的話看卡在哪裡。
（或是 main.log，直接用其他文字編輯器開應該也可。看不懂的話可以傳網路空間再丟連結上來）

另外一個可能問題是導言區，試試看將各子檔（自己） 添加於導言區的 \usepackage 移到 macros_preamble.tex
(因為我記得 standalone 有時會出現 bug，不會去讀子檔導言區)

[wiki 說明](https://github.com/sppmg/TW_Thesis_Template/wiki/%E5%88%9D%E7%B4%9A%E6%89%8B%E5%86%8A#%E5%8A%A0%E5%85%A5%E5%A5%97%E4%BB%B6%E5%8F%8A%E5%B0%8E%E8%A8%80%E5%8D%80)

**Comment by 7nightingale6** [comment]
![image](https://user-images.githubusercontent.com/84517015/120073254-3597ce00-c0ca-11eb-8d0f-dfa6f4e0ba85.png)
他有個[瀏覽紀錄] 是這個嗎

應該不是導言區的問題，我剛剛檢查過子檔，都沒有額外加的\usepackage

**Comment by sppmg** [comment]
我是指圖中紅字的區域（其實我想成你用 texwork，texmaker 跟 texstudio 很像，後者是我在 windows 上用的）。

由紅字看來應該是 standalone 套件導致中斷。

# 優先解決問題

1. 在 main.tex line 16（預設位置）有
```
\usepackage[subpreambles]{standalone} 
```
你改成 false 試試看停用 `subpreambles`（反正你已經要最後編譯了，而且據你說子檔導言區都空的。如果有的話通通移到
`macros_preamble.tex` ）

```
\usepackage[subpreambles=false]{standalone} 
```

2. 上面方法應該有效，不然檢查一下同路徑下應該存在 `main.sta` ，我猜測可能裡面有些錯誤，刪除它（以及其他自動生成檔案，使用 texmaker 的 clear 比較方便）應該有效。
3. 雖然說機率極小，可能是你系統上的套件損壞。更新 miktex 或是丟到 overleaf 上試試。（不得已再來嘗試這個 XD）

# 問題來源

這只是無聊研究用的，有空有興趣再說。
**不過我先說，我以前使用時其實就發現 `standalone` 有時候會有點異常，也是有可能裡面有些 bug。
發生頻率不高，但總有些套件還什麼的會觸發異常。**



在不停用 `subpreambles` 下，試試以下作法。

1. 如上所說，可能是 `main.sta` 異常。刪除試試是否可行。
2. 由 `main.tex` 逐一註解子檔，看看哪個子檔會出問題。

**Comment by 7nightingale6** [comment]
改成 false 就成功了
實在是太感謝大大了<(_ _)>
