### ISSUE TITLE
換頁之後文字縮排問題

### ISSUE THREAD

**Issue by jackpopp125** [sppmg/TW_Thesis_Template#22]
您好：
想請教一下，段落換頁之後如何對齊前一頁的縮排，我發現每換一頁文字縮排就會跑掉，謝謝

![image](https://user-images.githubusercontent.com/39873063/122633746-b61b7e80-d10c-11eb-8a05-6a41e1e54dd9.png)

**Comment by jackpopp125** [comment]
設成 \documentclass[oneside]{NCU_thesis} 好像就可以了？

**Comment by sppmg** [comment]
是的，這是左右頁造成的，因為書本內緣裝訂會壓縮邊距，所以一般都會將內緣加寬。
oneside 就假設不在側邊裝訂，所以左右邊距一樣。

如果你要維持雙面又要對齊，要去cls裡面設定頁邊。

晚點我用電腦再回哪行。

jackpopp125 ***@***.***> 於 2021年6月19日 週六 下午3:21 寫道：

**Comment by jackpopp125** [comment]
好的，再麻煩你了！謝謝！

**Comment by jackpopp125** [comment]
另外想請教目錄或圖片敘述產生的紅框要怎麼去除？
![image](https://user-images.githubusercontent.com/39873063/122640202-c0e80a80-d130-11eb-8825-0a39800fde6c.png)

**Comment by sppmg** [comment]
## 邊距的設定
邊距的設定位於 [thesis_base.cls L185](https://github.com/sppmg/TW_Thesis_Template/blob/f961234c216ad9542e276e2b767673b5f672c8cd/NCU_zh/thesis_base.cls#L185)。是由 geometry 套件提供的。
非 NCU 版有可能位於各校的 .cls 裡面。

或是你可以用 `\geometry{}` 指令在自己的設定區域去覆寫這個設定值。
(https://www.overleaf.com/learn/latex/Page_size_and_margins)


我建議你先查清楚校方規定。我有列在上面的通常都是學校規定的邊距，尤其是 NCU。

## 連結的紅框

紅框是 PDF 軟體顯示出來的，紙本不會印出。
不過如果你希望強制隱藏（因為有些閱讀器不會顯示），可以改 config.tex 裡面的 `pdfLinkBoxDisplay`
(https://github.com/sppmg/TW_Thesis_Template/wiki/%E5%88%9D%E7%B4%9A%E6%89%8B%E5%86%8A#pdf)

**Comment by jackpopp125** [comment]
好的，謝謝您的協助！
