### ISSUE TITLE
algorithm怎麼用?

### ISSUE THREAD

**Issue by micktsai** [sppmg/TW_Thesis_Template#25]
目前用overleaf編輯，但是不知道怎麼用algorithm的package
不管在哪個導言區或macros_preamble中使用
\usepackage{algorithm}
\usepackage{algorithmic}
都無法解決
請問該如何寫algorithm

**Comment by sppmg** [comment]
我得要下週三以後才能幫你測試。
不過以前有網友成功使用 algorithm2e （issue 中：
https://github.com/sppmg/TW_Thesis_Template/issues/1）。

查了一下資料，我猜你是把 environment 跟 package 搞錯了。

下面兩個網頁看一下，overleaf 的有完整範例。

1. https://www.overleaf.com/learn/latex/Algorithms

2. https://en.m.wikibooks.org/wiki/LaTeX/Algorithms

如果還是不行，請將錯誤訊息附上。
（只要貼錯誤的那幾行就好，不要全部log貼上來喔！）


micktsai ***@***.***> 於 2023年7月2日 週日 02:42 寫道：

**Comment by micktsai** [comment]
可以了 感謝!
