### ISSUE TITLE
奇頁與偶頁距離左邊距位置不同 與如何取消頁 "首章節名稱

### ISSUE THREAD

**Issue by brucetasy** [sppmg/TW_Thesis_Template#26]
請提供以下資訊：

1. 未修改的樣板是否有同樣狀況？  
2. 是否有錯誤訊息，有的話請提供。 
3. LaTeX 發行版(TeX Live / MikTeX)    **MikTeX**
4. 作業系統(Linux / Mac / Windows)   **Windows**
5. (可選)是否提供能產生問題的最小範例(MWE)，如經某小改動就導致樣板編譯錯誤，這能讓體定位問題點，也許能直接解決問題。
![Q001](https://github.com/sppmg/TW_Thesis_Template/assets/39981236/3375dc62-49e2-4bb5-880f-d8c376ec933b)

感謝您的協助與奉獻 !

**Comment by sppmg** [comment]
據我模糊的印象，應該添加 ``oneside`` 選項就可以了

例如在 ``main.tex`` 一開始的
```
\documentclass[]{NCU_thesis}
```

改成
```
\documentclass[oneside]{NCU_thesis}
```

------
不過我還是要提醒你，那間隙是設計給『裝訂成書籍』後的裝訂邊。
沒有這間隙的話很難閱讀內側文字，不然就要將兩邊頁邊都加寬。

**當然，如果只是因為規定不得不做那就無視吧～**
(不過學校規定要看清楚，記得不少學校是規定 ``twoside`` 樣式，但一般沒在排版的人不懂加上沒看規定....)

附註：
1. https://www.overleaf.com/learn/latex/Single_sided_and_double_sided_documents
2. 本樣板以 book class 為基底，所以預設是 ``twoside``，印象中有人改過 ``oneside`` 不會出問題。應該是會直接套用右頁設定。
3. 若改 ``oneside`` 後還想改頁邊，應該在導言區用  \geometry{〈options〉} 設定就可以了。(https://tex.stackexchange.com/a/130782)
   或是進 ``thesis_base.cls`` line 185 修改。
5. [geometry doc](https://ctan.mirror.twds.com.tw/tex-archive/macros/latex/contrib/geometry/geometry.pdf)

**Comment by brucetasy** [comment]
感謝您的回覆，依據指引修正 邊距終於不會形成奇偶遇不同。
再次感謝您 !


[image: REDO2.png]

sppmg ***@***.***> 於 2023年7月19日 週三 下午5:16寫道：
