### ISSUE TITLE
The watermark transparent problem on the first page with package eso-pic

### ISSUE THREAD

**Issue by Hsins** [sppmg/TW_Thesis_Template#3]
[Wiki](https://github.com/sppmg/TW_Thesis_Template/wiki/%E5%88%9D%E7%B4%9A%E6%89%8B%E5%86%8A#%E6%B5%AE%E6%B0%B4%E5%8D%B0) 頁中寫道：

套件 | bug
-- | --
background | 圖片可能覆蓋在 \includepdf 頁面之上。
eso-pix | 第一個顯示的浮水印永遠是 100% 不透明

關於這部分，實際上是因為 `tikz` 所產生的問題，詳細內容可以看 [tikz/eso-pic watermark isn't transparent on the first page](https://tex.stackexchange.com/questions/32184/tikz-eso-pic-watermark-isnt-transparent-on-the-first-page) 這篇回答，如果要修正這個問題，那麼應該修正 Package 引入的順序，使得 `tikz` 在 `eso-pic` 之前引入：

```latex
\RequirePackage{tikz}
\RequirePackage{eso-pic}
```

我自己的專案 [NTU-Thesis-Template](https://github.com/Hsins/NTU-Thesis-Template) 中使用上述的寫法，是可以第一頁也有透明度的，如下圖所示：

![image](https://user-images.githubusercontent.com/26391143/42419782-0e377670-82ee-11e8-80d3-0c5e5418ccad.png)

**Comment by sppmg** [comment]
感謝回報

那連結我以前好像看過，當時好像沒有  `user91669` 的留言。

不過看了我的 cls ，也是先引入 `tikz` 耶！（[這裡](https://github.com/sppmg/TW_Thesis_Template/blob/854e905dc2da1846866db1bb75c1f5c198847e43/NCU_zh/thesis_base.cls#L534)）

我之後研究下為何我的不行。搞不好還有其他套件影響？

**Comment by Hsins** [comment]
這篇 [Why does eso-pic turn off the Tikz text opacity?](https://tex.stackexchange.com/questions/174909/why-does-eso-pic-turn-off-the-tikz-text-opacity) 有則留言提到可能是老舊的 Package 造成的，我自己是 TexLive 2017/2018 透過 XeLaTeX 進行編譯都是正常的。

**Comment by sppmg** [comment]
非常感謝。
我拖到剛剛才來處理這個問題。
(因為我整個編譯就會出問題，然後反正有 background pkg 以及我現在也沒在用這功能，就懶得檢查了 。XD)

稍微搬移測試，發現問題肇因於 `pdfpages`。只要在它之前載入 `tikz` 就可以了

```tex
\RequirePackage{tikz}
\RequirePackage{pdfpages} 
```
