### ISSUE TITLE
清大論文格式需修改

### ISSUE THREAD

**Issue by tommyannypeter** [sppmg/TW_Thesis_Template#5]
@sppmg 大大，托你的福，我完成論文也順利畢業了。只是在審核的時候格式碰上了一點小問題，想提出為未來想用的學弟妹預作修改。
1) 清大電子檔審核不能有無內容的空白頁，即使有浮水印也不行，所以預設要有oneside。後來我印出來也是照用oneside，所以我不清楚繳交紙本是否可以雙面列印，但為了頁碼與電子檔相符，還是建議都使用oneside。
2) 封面好像不能有浮水印。我的電子檔審核是過了，但是影印部的阿姨好像說不行(我猜是為了美觀)，他印的時候自己檔案處理去掉了，但畢竟他自己弄去不乾淨(標題壓到浮水印)。我看其他學長姐的論文，也都是封面沒有浮水印，印內頁封面才有。
3) BibLatex格式用nature。或許是我不會設定，但原來用IEEE的格式，名字太多的時候不會自己縮成et al.，還會出現[online]之類教授覺得多餘且不明所以的文字。我改用nature的格式，教授就覺得沒問題。

**Comment by sppmg** [comment]
恭喜！恭喜！

原本我預定要使用的學弟妹後來好像沒用，所以我也不知道實際審核結果。

1. 用 oneside 會有頁面邊距的問題，可能會不合校方規定（oneside 文字兩邊是等寬的）。
另外就是頁首的章節標題（雖然這不重要 XD）。 LaTeX 還有一個選項；openany。這可以不限制章節從右頁開始，也就可以保持使用 twoside。

2. 封面浮水印可以比照臺大辦理。main.tex 中：
```tex
\input{titlepage}        % 封面
        \startWatermark
\input{titlepage} % 書名頁
```
簡單說就是 ，書名頁的部份複製一行（印兩次），然後讓浮水印從第二面開始
（我之後加上去）。

3. 其實我自己也是比較偏好 nature （我論文用的是 nature），IEEE 附加資訊較詳細，但可能會嫌繁雜（online 就是指網頁資料，可能因為變動性較高所以要求加吧！）。當初改為 IEEE 是因為用 LaTeX 的不少是工程學系，比較會要求用 IEEE。而用 nature 的*感覺上*會比較開放，不限定用什麼格式。所以基於方便性就設定為 IEEE 啦！

**Comment by tommyannypeter** [comment]
1) 我目前看了一些學長姐的論文，他們都是印單頁印刷等寬邊距，稍微查了一下好像也沒看到寫相關的規定。我覺得或許可以在wiki特別寫一下oneside和openany，我想應該蠻多人會遇到相關的問題，尤其是想雙面印刷省紙又不能有空白頁又找不到怎麼弄。><
2) 我整個沒發現可以修改浮水印位置(笑)。但我不確定連放兩頁封面在電子檔審核的時候會不會過。
3) 原來如此，不過現在大多數的參考資料都是網路上找得到的論文，我當時弄的時候就每個都有online，看了很礙眼XD

再次感謝大大，希望這個模板未來可以有更多人使用~
