### ISSUE TITLE
NCU.zh Some Questions

### ISSUE THREAD

**Issue by jzsyuan** [sppmg/TW_Thesis_Template#7]
1. 怎麼去掉章節跟章節間的空白頁,我已經修改了\setboolean{reallyBlankPage}{false}但依然存在
2. 怎麼修改listoffigure前面的標示原本為章節.第幾張圖，想改成 圖.第幾張圖

非常感謝您

**Comment by sppmg** [comment]
1. 用 oneside

https://github.com/sppmg/TW_Thesis_Template/wiki/FAQ#%E5%A6%82%E4%BD%95%E5%8D%B0%E6%88%90%E5%96%AE%E9%9D%A2

2. 是指圖號不分章節，從開始到結尾？


jzsyuan <notifications@github.com> 於 2019年5月1日 週三 下午5:01 寫道：

**Comment by sppmg** [comment]
1. 用 `openany` 
```tex 
\documentclass[openany]{NCU_thesis}
``` 

2. 是指圖號不分章節，從開始到結尾？

**Comment by jzsyuan** [comment]
sppmg 您好.
感謝您已經都解決了

**Comment by jzsyuan** [comment]
sppmg 您好，怎麼讓每頁都置中

**Comment by sppmg** [comment]
恭喜恭喜。
2. 的問題，我之前有查到[這個方法](https://tex.stackexchange.com/a/332913)
```tex
\setcounter{figure}{0}
\renewcommand{\thefigure}{\arabic{figure}}
```
不知道你是不是同法解決？

如果是中央的話，雖然校方給的範例是圖號連續編。但其實用 `chapter`.`section` 是可以通過的。
而且我自己覺得這樣比較清楚。以一本書來說，你不會希望整本書的圖都是連續編號的。
不過校方訂規格的人常常是就著 Word 的思路走而不是`排版`。
